{{- if eq .Values.cronjob.enabled true }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "general.name" . }}
  annotations:
  {{- toYaml .Values.annotations | nindent 4 }}
  labels:
    app: {{ regexReplaceAll "-exp-[a-zA-Z0-9]{1,10}$" (include "general.name" .) "" }}
  {{- include "general.labels" . | nindent 4 }}  
  {{- if .Values.labels  }}
  {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}    
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit | default "3" }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit | default "1" }}
  {{- if .Values.cronjob.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{- if .Values.annotations }}
            {{- toYaml .Values.annotations | nindent 12 }}
            {{- end }}
          labels:
            app: {{ regexReplaceAll "-exp-[a-zA-Z0-9]{1,10}$" (include "general.name" .) "" }}
            {{- include "general.labels" . | nindent 12 }} 
            {{- if .Values.labels  }}
            {{- toYaml .Values.labels | nindent 12 }}
            {{- end }}
        spec:
          ##### terminationGracePeriodSeconds block
          terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default "30" }}        
          ##### host network block           
          {{- if .Values.hostNetwork  }}
          hostNetwork: {{ .Values.hostNetwork }}
          {{- end }}        
          ##### pull secret block        
          {{- if .Values.imagePullSecrets  }}
          imagePullSecrets:
            {{- range .Values.imagePullSecrets }}
            - name: {{ . }}
            {{- end }}          
          {{- end }} 
          ##### affinity block
          {{- if .Values.affinity  }}
          affinity:
          {{- toYaml .Values.affinity | nindent 12 }}
          {{- end }}
          ##### tolerations block
          {{- if .Values.tolerations  }}
          tolerations:
          {{- toYaml .Values.tolerations | nindent 12 }}
          {{- end }}      
          ##### service acount block
          serviceAccountName: {{ include "general.name" . }}
          ##### security context block
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }} 
          ##### priority class block
          {{- if .Values.priorityClassName }}
          priorityClassName:  {{ .Values.priorityClassName }}
          {{- end }}   
          ##### host aliases block
          {{- if .Values.hostAliases  }}
          hostAliases:
          {{- range $key, $value := .Values.hostAliases }}
          - ip: {{ $key }}
            hostnames:
            -  {{ $value | quote }}
          {{- end }}  
          {{- end }} 
          restartPolicy: {{ .Values.cronjob.restartPolicy }}        
          {{- if .Values.initContainers  }}
          initContainers:
          {{ include "general.cronjobContainers" (dict "containerList" .Values.initContainers ) }}
          {{- end }}               
          containers:     
          {{ include "general.cronjobContainers" (dict "containerList" .Values.containers ) }} 
          ##### volumes
          {{- if .Values.volumes  }}
          volumes:
            {{- toYaml .Values.volumes | nindent 14 }} 
          {{- end }}   

{{- end }}
